INFO:emr.fhir_client:Epic FHIR tokens set successfully
INFO:services.comprehensive_emr_sync:Initialized ComprehensiveEMRSync for organization 1
INFO:services.comprehensive_emr_sync:Starting patient discovery from Epic FHIR
INFO:services.comprehensive_emr_sync:Retrieving patient erXuFYUfucBZaryVksYEcMg3 from Epic
INFO:services.comprehensive_emr_sync:Successfully retrieved patient erXuFYUfucBZaryVksYEcMg3
INFO:services.comprehensive_emr_sync:Retrieving patient eq081-VQEgP8drUUqCWzHfw3 from Epic
INFO:services.comprehensive_emr_sync:Successfully retrieved patient eq081-VQEgP8drUUqCWzHfw3
INFO:services.comprehensive_emr_sync:Retrieving patient eAB3mDIBBcyUKviyzrxsnAw3 from Epic
INFO:services.comprehensive_emr_sync:Successfully retrieved patient eAB3mDIBBcyUKviyzrxsnAw3
INFO:services.comprehensive_emr_sync:Retrieving patient eJBJ0FuCdUgPRFYOdBMOjGQx from Epic
ERROR:emr.fhir_client:Client error, not retrying: HTTP 404 error: 404 Client Error: Not Found for url: https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/Patient/eJBJ0FuCdUgPRFYOdBMOjGQx
WARNING:services.comprehensive_emr_sync:Could not retrieve patient eJBJ0FuCdUgPRFYOdBMOjGQx
INFO:services.comprehensive_emr_sync:Retrieving patient eWY1-V1J5NfkwZrqcqcwl7_x from Epic
ERROR:emr.fhir_client:Client error, not retrying: HTTP 404 error: 404 Client Error: Not Found for url: https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/Patient/eWY1-V1J5NfkwZrqcqcwl7_x
WARNING:services.comprehensive_emr_sync:Could not retrieve patient eWY1-V1J5NfkwZrqcqcwl7_x
INFO:services.comprehensive_emr_sync:Retrieving patient eLZPOqNUgFXgQ_YRgvMJCCUZ from Epic
ERROR:emr.fhir_client:Client error, not retrying: HTTP 404 error: 404 Client Error: Not Found for url: https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/Patient/eLZPOqNUgFXgQ_YRgvMJCCUZ
WARNING:services.comprehensive_emr_sync:Could not retrieve patient eLZPOqNUgFXgQ_YRgvMJCCUZ
INFO:services.comprehensive_emr_sync:Retrieving patient eGOLhPUiQr5KKD2v9W3cXwAd from Epic
ERROR:emr.fhir_client:Client error, not retrying: HTTP 404 error: 404 Client Error: Not Found for url: https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/Patient/eGOLhPUiQr5KKD2v9W3cXwAd
WARNING:services.comprehensive_emr_sync:Could not retrieve patient eGOLhPUiQr5KKD2v9W3cXwAd
INFO:services.comprehensive_emr_sync:Retrieving patient eCGMnHhT_sE5tHo4l5PYbp2K from Epic
ERROR:emr.fhir_client:Client error, not retrying: HTTP 404 error: 404 Client Error: Not Found for url: https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/Patient/eCGMnHhT_sE5tHo4l5PYbp2K
WARNING:services.comprehensive_emr_sync:Could not retrieve patient eCGMnHhT_sE5tHo4l5PYbp2K
INFO:services.comprehensive_emr_sync:Retrieved 3 Epic sandbox patients
INFO:services.comprehensive_emr_sync:Discovered 3 patients from Epic
INFO:services.comprehensive_emr_sync:Created new patient: Camila Maria Lopez
ERROR:services.comprehensive_emr_sync:Error importing/updating patient: (psycopg2.errors.NotNullViolation) null value in column "mrn" of relation "patient" violates not-null constraint
DETAIL:  Failing row contains (4, null, Camila Maria Lopez, 1987-09-12, female, null, null, null, 1, erXuFYUfucBZaryVksYEcMg3, 2025-09-02 19:17:08.887886, 2025-09-02 19:17:08.887888, null, 2025-09-02 19:17:08.885965, null).

[SQL: INSERT INTO patient (mrn, name, date_of_birth, gender, phone, email, address, org_id, epic_patient_id, fhir_patient_resource, last_fhir_sync, fhir_version_id, created_at, updated_at) VALUES (%(mrn)s, %(name)s, %(date_of_birth)s, %(gender)s, %(phone)s, %(email)s, %(address)s, %(org_id)s, %(epic_patient_id)s, %(fhir_patient_resource)s, %(last_fhir_sync)s, %(fhir_version_id)s, %(created_at)s, %(updated_at)s) RETURNING patient.id]
[parameters: {'mrn': None, 'name': 'Camila Maria Lopez', 'date_of_birth': datetime.date(1987, 9, 12), 'gender': 'female', 'phone': None, 'email': None, 'address': None, 'org_id': 1, 'epic_patient_id': 'erXuFYUfucBZaryVksYEcMg3', 'fhir_patient_resource': None, 'last_fhir_sync': datetime.datetime(2025, 9, 2, 19, 17, 8, 885965), 'fhir_version_id': None, 'created_at': datetime.datetime(2025, 9, 2, 19, 17, 8, 887886), 'updated_at': datetime.datetime(2025, 9, 2, 19, 17, 8, 887888)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO:services.comprehensive_emr_sync:Created new patient: Derrick Lin
ERROR:services.comprehensive_emr_sync:Error importing/updating patient: (psycopg2.errors.NotNullViolation) null value in column "mrn" of relation "patient" violates not-null constraint
DETAIL:  Failing row contains (5, null, Derrick Lin, 1973-06-03, male, null, null, null, 1, eq081-VQEgP8drUUqCWzHfw3, 2025-09-02 19:17:08.996407, 2025-09-02 19:17:08.996409, null, 2025-09-02 19:17:08.995585, null).

[SQL: INSERT INTO patient (mrn, name, date_of_birth, gender, phone, email, address, org_id, epic_patient_id, fhir_patient_resource, last_fhir_sync, fhir_version_id, created_at, updated_at) VALUES (%(mrn)s, %(name)s, %(date_of_birth)s, %(gender)s, %(phone)s, %(email)s, %(address)s, %(org_id)s, %(epic_patient_id)s, %(fhir_patient_resource)s, %(last_fhir_sync)s, %(fhir_version_id)s, %(created_at)s, %(updated_at)s) RETURNING patient.id]
[parameters: {'mrn': None, 'name': 'Derrick Lin', 'date_of_birth': datetime.date(1973, 6, 3), 'gender': 'male', 'phone': None, 'email': None, 'address': None, 'org_id': 1, 'epic_patient_id': 'eq081-VQEgP8drUUqCWzHfw3', 'fhir_patient_resource': None, 'last_fhir_sync': datetime.datetime(2025, 9, 2, 19, 17, 8, 995585), 'fhir_version_id': None, 'created_at': datetime.datetime(2025, 9, 2, 19, 17, 8, 996407), 'updated_at': datetime.datetime(2025, 9, 2, 19, 17, 8, 996409)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO:services.comprehensive_emr_sync:Created new patient: Desiree Caroline Powell
ERROR:services.comprehensive_emr_sync:Error importing/updating patient: (psycopg2.errors.NotNullViolation) null value in column "mrn" of relation "patient" violates not-null constraint
DETAIL:  Failing row contains (6, null, Desiree Caroline Powell, 2014-11-14, female, null, null, null, 1, eAB3mDIBBcyUKviyzrxsnAw3, 2025-09-02 19:17:09.129229, 2025-09-02 19:17:09.129232, null, 2025-09-02 19:17:09.12846, null).

[SQL: INSERT INTO patient (mrn, name, date_of_birth, gender, phone, email, address, org_id, epic_patient_id, fhir_patient_resource, last_fhir_sync, fhir_version_id, created_at, updated_at) VALUES (%(mrn)s, %(name)s, %(date_of_birth)s, %(gender)s, %(phone)s, %(email)s, %(address)s, %(org_id)s, %(epic_patient_id)s, %(fhir_patient_resource)s, %(last_fhir_sync)s, %(fhir_version_id)s, %(created_at)s, %(updated_at)s) RETURNING patient.id]
[parameters: {'mrn': None, 'name': 'Desiree Caroline Powell', 'date_of_birth': datetime.date(2014, 11, 14), 'gender': 'female', 'phone': None, 'email': None, 'address': None, 'org_id': 1, 'epic_patient_id': 'eAB3mDIBBcyUKviyzrxsnAw3', 'fhir_patient_resource': None, 'last_fhir_sync': datetime.datetime(2025, 9, 2, 19, 17, 9, 128460), 'fhir_version_id': None, 'created_at': datetime.datetime(2025, 9, 2, 19, 17, 9, 129229), 'updated_at': datetime.datetime(2025, 9, 2, 19, 17, 9, 129232)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO:services.comprehensive_emr_sync:Discovery and sync completed: 0 patients synced, 0 screenings updated